services:
  agent-service:
    container_name: agent-service
    build: ./agent-service
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

networks:
  app_network:
    driver: bridge
